name: Unity CI — тесты и билд

on:
  push:
    paths:
      - '**.cs'
      - 'Assets/**'
      - 'ProjectSettings/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: 🎮 Run Unity Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode: [EditMode, PlayMode]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.testMode }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: Library-
      - name: Run tests (${{ matrix.testMode }})
        id: tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          testMode: ${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Tests-${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}

  build:
    name: 🛠 Build Project
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [StandaloneWindows64, WebGL]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.platform }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: Library-
      - name: Build for ${{ matrix.platform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.platform }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.platform }}
          path: build/${{ matrix.platform }}
